site_name: Feirm Documentation
site_url: https://docs.feirm.com/
theme:
  name: 'material'
  logo: 'images/feirm.png'
  favicon: 'images/favicon.ico'
nav:
  - Home: index.md
  - Blockchain:
    - Overview: blockchain/overview.md
  - Kayda:
    - Overview: kayda/overview.md
    - Features: kayda/features.md
    - Technical Overview: kayda/technical-overview.md
  - Marketplace:
    - Overview: marketplace/overview.md
    - Centralised Layer: marketplace/centralised-layer.md
    - Cryptography Layer: marketplace/cryptography-layer.md
extra_css:
  - 'stylesheets/extra.css'
