site_name: Feirm Documentation
theme:
  name: 'material'
nav:
  - Home: index.md
  - Running a Node:
    - Overview: running-a-node/overview.md
    - Node Setup: running-a-node/node-setup.md
extra_css:
  - 'stylesheets/extra.css'
