site_name: Feirm Documentation
site_url: https://docs.feirm.com/
theme:
  name: 'material'
  logo: 'images/feirm.png'
  favicon: 'images/favicon.ico'
nav:
  - Introduction to Feirm: index.md
  - Downloads: downloads.md
  - Support: support.md
  - Blockchain:
    - Overview: blockchain/overview.md
  - Kayda:
    - Overview: kayda/overview.md
    - Features: kayda/features.md
    - Technical Overview: kayda/technical-overview.md
  - Platform:
    - Overview: platform/overview.md
    - Centralised Layer: platform/centralised-layer.md
    - Cryptography Layer: platform/cryptography-layer.md
extra_css:
  - 'stylesheets/extra.css'
